research-project:
  ms1:
    name: "RM1"
    date: 2025-09-05
  ms2:
    name: "RM2"
    date: 2025-09-19
  ms3:
    name: "RM3"
    date: 2025-10-06
  ms4:
    name: "RM4"
    date: 2025-10-20
  ms5:
    name: "RM5"
    date: 2025-12-12
    time: "in class"
  ms6:
    name: "RM6"
    date: 2025-12-19